# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os

from dayz_admin_tools.utilities.files.json import JSONManager
from dayz_admin_tools.utilities.files.xml import XMLManager
from src.config import config
from pathlib import Path
from src.forms import mainConfig

from dayz_admin_tools.utilities.economy.Types import Types
from dayz_admin_tools.utilities.traders.expansion.Items import Items
from PyQt6 import QtCore, QtGui, QtWidgets
#TODO: Added these Additional Imports
from PyQt6.QtWidgets import QFileDialog, QWidget, QMessageBox, QMainWindow


#TODO: Changed parent window to QMainWindow from object
class Ui_MainWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self, parent=None)
        self._loaded = None
        self.parent = None
        self._profiles_directory = None
        self._market_dir = None
        self._trader_dir = None
        self._json_directory = None
        self._xml_directory = None
        self._configWindow = mainConfig.Ui_ConfigWindow()


    def setupUi(self, MainWindow):

        # call configWindow setupUI

        self._configWindow.setupUi(self._configWindow)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 813)
        #TODO: Added this next line
        self._parent = MainWindow
        #TODO: Added this next line
        self._loaded = False
        #TODO: Added this next line
        self._profiles_directory, self._market_dir, self._trader_dir, self._json_directory, self._xml_directory = config.loadConfig()

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_market_config = QtWidgets.QWidget()
        self.tab_market_config.setObjectName("tab_market_config")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_market_config)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_13 = QtWidgets.QLabel(parent=self.tab_market_config)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.tab_market_config)
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_className = QtWidgets.QLabel(parent=self.frame)
        self.label_className.setObjectName("label_className")
        self.gridLayout_2.addWidget(self.label_className, 0, 1, 1, 1)
        self.lineEdit_maxstock = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_maxstock.setObjectName("lineEdit_maxstock")
        self.gridLayout_2.addWidget(self.lineEdit_maxstock, 2, 2, 1, 1)
        self.lineEdit_maxprice = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_maxprice.setObjectName("lineEdit_maxprice")
        self.gridLayout_2.addWidget(self.lineEdit_maxprice, 1, 2, 1, 1)
        self.lineEdit_classname = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_classname.setObjectName("lineEdit_classname")
        self.gridLayout_2.addWidget(self.lineEdit_classname, 0, 2, 1, 3)
        self.lineEdit_quantitypercent = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_quantitypercent.setObjectName("lineEdit_quantitypercent")
        self.gridLayout_2.addWidget(self.lineEdit_quantitypercent, 3, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 3, 1, 1)
        self.label_minprice = QtWidgets.QLabel(parent=self.frame)
        self.label_minprice.setObjectName("label_minprice")
        self.gridLayout_2.addWidget(self.label_minprice, 1, 3, 1, 1)
        self.lineEdit_sellpricepercent = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_sellpricepercent.setObjectName("lineEdit_sellpricepercent")
        self.gridLayout_2.addWidget(self.lineEdit_sellpricepercent, 3, 2, 1, 1)
        self.pushButton_searchclasses = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_searchclasses.setObjectName("pushButton_searchclasses")
        self.gridLayout_2.addWidget(self.pushButton_searchclasses, 0, 5, 1, 1)
        self.label_sellpricepercent = QtWidgets.QLabel(parent=self.frame)
        self.label_sellpricepercent.setObjectName("label_sellpricepercent")
        self.gridLayout_2.addWidget(self.label_sellpricepercent, 3, 1, 1, 1)
        self.lineEdit_minprice = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_minprice.setObjectName("lineEdit_minprice")
        self.gridLayout_2.addWidget(self.lineEdit_minprice, 1, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 3, 1, 1)
        self.label_maxprice = QtWidgets.QLabel(parent=self.frame)
        self.label_maxprice.setObjectName("label_maxprice")
        self.gridLayout_2.addWidget(self.label_maxprice, 1, 1, 1, 1)
        self.lineEdit_minstock = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_minstock.setObjectName("lineEdit_minstock")
        self.gridLayout_2.addWidget(self.lineEdit_minstock, 2, 4, 1, 1)
        self.label_maxstock = QtWidgets.QLabel(parent=self.frame)
        self.label_maxstock.setObjectName("label_maxstock")
        self.gridLayout_2.addWidget(self.label_maxstock, 2, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget1 = QtWidgets.QTabWidget(parent=self.widget)
        self.tabWidget1.setObjectName("tabWidget1")
        self.tabWidgetPage_attachments = QtWidgets.QWidget()
        self.tabWidgetPage_attachments.setObjectName("tabWidgetPage_attachments")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabWidgetPage_attachments)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_sourceattachfile = QtWidgets.QLabel(parent=self.tabWidgetPage_attachments)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sourceattachfile.sizePolicy().hasHeightForWidth())
        self.label_sourceattachfile.setSizePolicy(sizePolicy)
        self.label_sourceattachfile.setMaximumSize(QtCore.QSize(16777215, 61))
        self.label_sourceattachfile.setObjectName("label_sourceattachfile")
        self.horizontalLayout_5.addWidget(self.label_sourceattachfile)
        self.comboBox_attachfile_source = QtWidgets.QComboBox(parent=self.tabWidgetPage_attachments)
        self.comboBox_attachfile_source.setObjectName("comboBox_attachfile_source")
        self.horizontalLayout_5.addWidget(self.comboBox_attachfile_source)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.frame_attachments = QtWidgets.QFrame(parent=self.tabWidgetPage_attachments)
        self.frame_attachments.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame_attachments.setLineWidth(1)
        self.frame_attachments.setObjectName("frame_attachments")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_attachments)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_availattach = QtWidgets.QLabel(parent=self.frame_attachments)
        self.label_availattach.setObjectName("label_availattach")
        self.gridLayout_3.addWidget(self.label_availattach, 0, 0, 1, 1)
        self.label_addedattach = QtWidgets.QLabel(parent=self.frame_attachments)
        self.label_addedattach.setObjectName("label_addedattach")
        self.gridLayout_3.addWidget(self.label_addedattach, 0, 2, 1, 1)
        self.listWidget_attachments_available = QtWidgets.QListWidget(parent=self.frame_attachments)
        self.listWidget_attachments_available.setObjectName("listWidget_attachments_available")
        self.gridLayout_3.addWidget(self.listWidget_attachments_available, 1, 0, 1, 1)
        self.pushButton_attachment_add = QtWidgets.QPushButton(parent=self.frame_attachments)
        self.pushButton_attachment_add.setObjectName("pushButton_attachment_add")
        self.gridLayout_3.addWidget(self.pushButton_attachment_add, 1, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignTop)
        self.listWidget_attachments_added = QtWidgets.QListWidget(parent=self.frame_attachments)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_attachments_added.sizePolicy().hasHeightForWidth())
        self.listWidget_attachments_added.setSizePolicy(sizePolicy)
        self.listWidget_attachments_added.setObjectName("listWidget_attachments_added")
        self.gridLayout_3.addWidget(self.listWidget_attachments_added, 1, 2, 1, 1)
        self.pushButton_attachment_remove = QtWidgets.QPushButton(parent=self.frame_attachments)
        self.pushButton_attachment_remove.setObjectName("pushButton_attachment_remove")
        self.gridLayout_3.addWidget(self.pushButton_attachment_remove, 2, 2, 1, 1)
        self.gridLayout_8.addWidget(self.frame_attachments, 1, 0, 1, 1)
        self.tabWidget1.addTab(self.tabWidgetPage_attachments, "")
        self.tabWidgetPage_variants = QtWidgets.QWidget()
        self.tabWidgetPage_variants.setObjectName("tabWidgetPage_variants")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabWidgetPage_variants)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_variants = QtWidgets.QFrame(parent=self.tabWidgetPage_variants)
        self.frame_variants.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame_variants.setLineWidth(1)
        self.frame_variants.setObjectName("frame_variants")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_variants)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_availvariants = QtWidgets.QLabel(parent=self.frame_variants)
        self.label_availvariants.setObjectName("label_availvariants")
        self.gridLayout_5.addWidget(self.label_availvariants, 0, 0, 1, 1)
        self.label_addedvariants = QtWidgets.QLabel(parent=self.frame_variants)
        self.label_addedvariants.setObjectName("label_addedvariants")
        self.gridLayout_5.addWidget(self.label_addedvariants, 0, 2, 1, 1)
        self.listWidget_variants_available = QtWidgets.QListWidget(parent=self.frame_variants)
        self.listWidget_variants_available.setObjectName("listWidget_variants_available")
        self.gridLayout_5.addWidget(self.listWidget_variants_available, 1, 0, 1, 1)
        self.pushButton_variants_add = QtWidgets.QPushButton(parent=self.frame_variants)
        self.pushButton_variants_add.setObjectName("pushButton_variants_add")
        self.gridLayout_5.addWidget(self.pushButton_variants_add, 1, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignTop)
        self.listWidget_variants_added = QtWidgets.QListWidget(parent=self.frame_variants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_variants_added.sizePolicy().hasHeightForWidth())
        self.listWidget_variants_added.setSizePolicy(sizePolicy)
        self.listWidget_variants_added.setObjectName("listWidget_variants_added")
        self.gridLayout_5.addWidget(self.listWidget_variants_added, 1, 2, 1, 1)
        self.pushButton_variants_remove = QtWidgets.QPushButton(parent=self.frame_variants)
        self.pushButton_variants_remove.setObjectName("pushButton_variants_remove")
        self.gridLayout_5.addWidget(self.pushButton_variants_remove, 2, 2, 1, 1)
        self.gridLayout_7.addWidget(self.frame_variants, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_sourcevariantsfile = QtWidgets.QLabel(parent=self.tabWidgetPage_variants)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sourcevariantsfile.sizePolicy().hasHeightForWidth())
        self.label_sourcevariantsfile.setSizePolicy(sizePolicy)
        self.label_sourcevariantsfile.setMaximumSize(QtCore.QSize(16777215, 61))
        self.label_sourcevariantsfile.setObjectName("label_sourcevariantsfile")
        self.horizontalLayout_6.addWidget(self.label_sourcevariantsfile)
        self.comboBox_variantsfile_source = QtWidgets.QComboBox(parent=self.tabWidgetPage_variants)
        self.comboBox_variantsfile_source.setObjectName("comboBox_variantsfile_source")
        self.horizontalLayout_6.addWidget(self.comboBox_variantsfile_source)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.tabWidget1.addTab(self.tabWidgetPage_variants, "")
        self.gridLayout_6.addWidget(self.tabWidget1, 1, 0, 1, 1)
        self.pushButton_newitem = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_newitem.setObjectName("pushButton_newitem")
        self.gridLayout_6.addWidget(self.pushButton_newitem, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 0, 1, 3, 1)
        self.comboBox_market_filename = QtWidgets.QComboBox(parent=self.tab_market_config)
        self.comboBox_market_filename.setObjectName("comboBox_market_filename")
        self.gridLayout_4.addWidget(self.comboBox_market_filename, 1, 0, 1, 1)
        self.treeView = QtWidgets.QTreeView(parent=self.tab_market_config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setObjectName("treeView")
        self.gridLayout_4.addWidget(self.treeView, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_market_config, "")
        self.tab_economy_config = QtWidgets.QWidget()
        self.tab_economy_config.setObjectName("tab_economy_config")
        self.label_comingsoon = QtWidgets.QLabel(parent=self.tab_economy_config)
        self.label_comingsoon.setGeometry(QtCore.QRect(360, 300, 321, 71))
        self.label_comingsoon.setObjectName("label_comingsoon")
        self.tabWidget.addTab(self.tab_economy_config, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setMovable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1076, 24))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(parent=self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Config = QtWidgets.QMenu(parent=self.menuBar)
        self.menu_Config.setObjectName("menu_Config")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        icon = QtGui.QIcon()
        #TODO: Updated path for config
        icon.addPixmap(QtGui.QPixmap(f"{os.path.dirname(os.path.dirname(os.path.realpath(__file__)))}/config/resources/cross-script.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionConfig = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        #TODO: Updated path for config
        icon1.addPixmap(QtGui.QPixmap(f"{os.path.dirname(os.path.dirname(os.path.realpath(__file__)))}/config/resources/blue-folder--pencil.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionConfig.setIcon(icon1)
        self.actionConfig.setObjectName("actionConfig")
        self.action_Validate = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        #TODO: Updated path for config
        icon2.addPixmap(QtGui.QPixmap(f"{os.path.dirname(os.path.dirname(os.path.realpath(__file__)))}/config/resources/chart-up-color.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.action_Validate.setIcon(icon2)
        self.action_Validate.setObjectName("action_Validate")
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addAction(self.actionConfig)
        self.toolBar.addAction(self.action_Validate)
        self.menu_File.addAction(self.actionExit)
        self.menu_Config.addAction(self.actionConfig)
        self.menu_Config.addAction(self.action_Validate)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Config.menuAction())

        self.retranslateUi(MainWindow)

        # TODO: Added All the Slots/Signal wiring
        self.actionExit.triggered.connect(self._closeform)
        self.actionConfig.triggered.connect(self._loadconfig)
        self.action_Validate.triggered.connect(self._validate)
        # self.pushButton_ProfileLocation.clicked['bool'].connect(self._getProfileLocation)  # type: ignore
        # self.pushButton_marketdirectory.clicked['bool'].connect(self._getMarketLocation)  # type: ignore
        # self.pushButton_tradersdirectory.clicked['bool'].connect(self._getTraderLocation)  # type: ignore
        # self.pushButton_addJSON.clicked['bool'].connect(self._addJSONLocation)  # type: ignore
        # self.pushButton_removeJSON.clicked['bool'].connect(self._removeJSONLocation)  # type: ignore
        # self.pushButton_addXML.clicked['bool'].connect(self._addXMLLocation)  # type: ignore
        # self.pushButton_removeXML.clicked['bool'].connect(self._removeXMLLocation)  # type: ignore
        # self.pushButton_Close.clicked['bool'].connect(self._closeForm)  # type: ignore

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget1.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox_market_filename, self.treeView)
        MainWindow.setTabOrder(self.treeView, self.lineEdit_classname)
        MainWindow.setTabOrder(self.lineEdit_classname, self.pushButton_searchclasses)
        MainWindow.setTabOrder(self.pushButton_searchclasses, self.lineEdit_maxprice)
        MainWindow.setTabOrder(self.lineEdit_maxprice, self.lineEdit_minprice)
        MainWindow.setTabOrder(self.lineEdit_minprice, self.lineEdit_maxstock)
        MainWindow.setTabOrder(self.lineEdit_maxstock, self.lineEdit_minstock)
        MainWindow.setTabOrder(self.lineEdit_minstock, self.lineEdit_sellpricepercent)
        MainWindow.setTabOrder(self.lineEdit_sellpricepercent, self.lineEdit_quantitypercent)
        MainWindow.setTabOrder(self.lineEdit_quantitypercent, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.comboBox_attachfile_source)
        MainWindow.setTabOrder(self.comboBox_attachfile_source, self.listWidget_attachments_available)
        MainWindow.setTabOrder(self.listWidget_attachments_available, self.pushButton_attachment_add)
        MainWindow.setTabOrder(self.pushButton_attachment_add, self.listWidget_attachments_added)
        MainWindow.setTabOrder(self.listWidget_attachments_added, self.pushButton_attachment_remove)
        MainWindow.setTabOrder(self.pushButton_attachment_remove, self.comboBox_variantsfile_source)
        MainWindow.setTabOrder(self.comboBox_variantsfile_source, self.listWidget_variants_available)
        MainWindow.setTabOrder(self.listWidget_variants_available, self.pushButton_variants_add)
        MainWindow.setTabOrder(self.pushButton_variants_add, self.listWidget_variants_added)
        MainWindow.setTabOrder(self.listWidget_variants_added, self.pushButton_variants_remove)
        MainWindow.setTabOrder(self.pushButton_variants_remove, self.pushButton_newitem)
        MainWindow.setTabOrder(self.pushButton_newitem, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        #TODO: Changed the WindowTitle
        MainWindow.setWindowTitle(_translate("MainWindow", "DayZ Admin Tool Manager"))
        self.label_13.setText(_translate("MainWindow", "Market File Name"))
        self.label_className.setText(_translate("MainWindow", "ClassName:"))
        self.label_6.setText(_translate("MainWindow", "Quantity %:"))
        self.label_minprice.setText(_translate("MainWindow", "Min Price:"))
        self.pushButton_searchclasses.setText(_translate("MainWindow", "..."))
        self.label_sellpricepercent.setText(_translate("MainWindow", "Sell Price %:"))
        self.label_5.setText(_translate("MainWindow", "Min Stock:"))
        self.label_maxprice.setText(_translate("MainWindow", "Max Price:"))
        self.label_maxstock.setText(_translate("MainWindow", "Max Stock:"))
        self.label_sourceattachfile.setText(_translate("MainWindow", "Source File"))
        self.label_availattach.setText(_translate("MainWindow", "Available Attachments"))
        self.label_addedattach.setText(_translate("MainWindow", "Added Attachments"))
        self.pushButton_attachment_add.setText(_translate("MainWindow", ">>"))
        self.pushButton_attachment_remove.setText(_translate("MainWindow", "Remove"))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tabWidgetPage_attachments), _translate("MainWindow", "Attachments"))
        self.label_availvariants.setText(_translate("MainWindow", "Available Variants"))
        self.label_addedvariants.setText(_translate("MainWindow", "Added Variants"))
        self.pushButton_variants_add.setText(_translate("MainWindow", ">>"))
        self.pushButton_variants_remove.setText(_translate("MainWindow", "Remove"))
        self.label_sourcevariantsfile.setText(_translate("MainWindow", "Source File"))
        self.tabWidget1.setTabText(self.tabWidget1.indexOf(self.tabWidgetPage_variants), _translate("MainWindow", "Variants"))
        self.pushButton_newitem.setText(_translate("MainWindow", "&New"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_market_config), _translate("MainWindow", "Market Config"))
        self.label_comingsoon.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt; color:#e1be00;\">Coming Soon</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_economy_config), _translate("MainWindow", "Economy Config"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Config.setTitle(_translate("MainWindow", "&Utilities"))
        self.actionExit.setText(_translate("MainWindow", "E&xit!"))
        self.actionConfig.setText(_translate("MainWindow", "Config!"))
        self.actionConfig.setToolTip(_translate("MainWindow", "Set Application Configuration"))
        self.action_Validate.setText(_translate("MainWindow", "&Validate!"))
        self.action_Validate.setToolTip(_translate("MainWindow", "Validate Configurations!"))

        #TODO: Added all code down to Main

        # Market Tab is loaded first, initialize the Market Files
        self._load_marketfiles()

    def _loadconfig(self):
        #config.setconfig()
        self._configWindow.show()
        self._profiles_directory, self._market_dir, self._trader_dir, self._json_directory, self._xml_directory = config.loadConfig()

    def _load_marketfiles(self):
        if self._market_dir is not None:
            ret, files = Items.find_item_files(self._market_dir)
            if ret:
                file_sort = []
                for file in files:
                    file_sort.append(Path(file).name)
                file_sort = sorted(file_sort)
                self.comboBox_market_filename.addItems(file_sort)

    def _closeform(self):
        # Save Configuration File Info

        self._parent.close()
        return

    def _validate(self):
        raise NotImplementedError("Validate Method is not complete yet")
        # create a new QT form to display the terminal output
        profiles_directory, market_dir, trader_dir, json_directory, xml_directory = config.loadConfig()
        for path in json_directory:
            resp, count, files = JSONManager.validate_files(path)

        for path in xml_directory:
            resp, count, files = XMLManager.validate_files(path)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
